# Generated by Django 5.0.1 on 2024-01-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
